version: "3"

services:
  backend:
    build: ./
    container_name: shop_container
    working_dir: /Yulia_shop
    restart: always
    command:
      - ./commands/start_server_${MODE}.sh
    ports:
      - ${LOCAL_PORT}:${WSGI_PORT}
    volumes:
      - ./src:/Yulia_shop/src
      - static_content:/Yulia_shop/src/static
      - media_content:/Yulia_shop/src/media
    entrypoint: ["/bin/bash", "./commands/start_server_${MODE}.sh"]
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "5001:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
#
#  mongodb:
#    image: arm64v8/mongo
#    ports:
#      - 27017:27017
#    container_name: mongo_db_container
#    command: [ "--bind_ip_all" ]
#    volumes:
#      - mongo_data:/data/db
#    restart: always
#    env_file:
#      - .env

  nginx:
    image: nginx:1.19
    volumes:
      - static_content:/Yulia-shop/src/static
      - media_content:/Yulia-shop/src/media
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    depends_on:
      - backend


volumes:
  pg_data: { }
  pgadmin_data: { }
#  mongo_data: { }
  static_content: { }
  media_content: { }

